version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/validator"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    ignore:
      - update-types: 
          - "version-update:semver-patch"
