services:
  tor:
    image: dperson/torproxy
    command: -n
    healthcheck:
      test: ["CMD", "sh", "-c", "curl --silent --fail --socks5-hostname localhost:9050 http://example.com"]
      interval: 10s
      timeout: 10s
      retries: 30

  yggdrasil:
    build: yggdrasil
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      # Space-separated list of Yggdrasil peer URIs, e.g. "tcp://host1:port tcp://host2:port"
      - YGGDRASIL_PEERS=tls://ygg.jjolly.dev:3443 tls://mo.us.ygg.triplebit.org:993 tls://ygg.mnpnk.com:443
    healthcheck:
      test: ["CMD", "sh", "-c", "curl --silent --fail http://[21e:a51c:885b:7db0:166e:927:98cd:d186]/"] # Yggdrasil Web directory
      interval: 5s
      timeout: 2s
      retries: 10

  smp-client:
    build: smp-client
    network_mode: "service:yggdrasil"
    depends_on:
      yggdrasil:
        condition: service_healthy
      tor:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "80"]
      interval: 5s
      timeout: 2s
      retries: 10

  validator:
    build:
      context: validator
      target: dev
    env_file:
      - .env
    environment:
      - SMP_CLIENT_URI=ws://localhost:80
      - SUPABASE_SERVERS_TABLE_NAME=v_server_summaries
      - SUPABASE_SERVERS_STATUS_TABLE_NAME=server_statuses
      - TOR_SOCKS5_PROXY=socks5h://tor:9050
      # - SUPABASE_URL=<to be filled in .env>
      # - SUPABASE_KEY=<to be filled in .env>
    depends_on:
      smp-client:
        condition: service_healthy
      tor:
        condition: service_healthy
    network_mode: "service:smp-client"
    working_dir: /workspace
    volumes:
      - .:/workspace
    command: ["sleep", "infinity"]
